-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Sales_transaction"
(
    "Transaction_id" integer NOT NULL,
    "Date" date,
    "Time" time without time zone,
    "Sales_outlet_id" integer,
    "Staff_id" integer,
    "Customer_id" integer,
    "Product_id" integer,
    "Quantity" integer,
    "Price" numeric,
    PRIMARY KEY ("Transaction_id")
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    "Product_id" integer NOT NULL,
    "Type" text,
    "Product" text,
    "Description" text,
    "Price" numeric,
    PRIMARY KEY ("Product_id")
);

CREATE TABLE IF NOT EXISTS public.sales_detail
(
    "Product_id" integer NOT NULL,
    "Transaction_id" integer NOT NULL,
    "Price" numeric,
    "Quantity" integer,
    PRIMARY KEY ("Product_id", "Transaction_id")
);

CREATE TABLE IF NOT EXISTS public.product_type
(
    "Type" text NOT NULL,
    "Category" text,
    PRIMARY KEY ("Type")
);

ALTER TABLE IF EXISTS public."Product"
    ADD FOREIGN KEY ("Type")
    REFERENCES public.product_type ("Type") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_detail
    ADD FOREIGN KEY ("Transaction_id")
    REFERENCES public."Sales_transaction" ("Transaction_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_detail
    ADD FOREIGN KEY ("Product_id")
    REFERENCES public."Product" ("Product_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;